name: release-main

on:
    push:
        branches: ["main"]

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get Week Number
              id: get_week
              shell: bash
              run: |
                  WEEK_NUMBER=$(date -u '+%V')
                  echo "week_number=${WEEK_NUMBER}" >> $GITHUB_OUTPUT

            - name: Configure Git Credentials
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - uses: actions/cache@v4
              with:
                  key: mkdocs-material-${{ steps.get_week.outputs.week_number }}
                  path: .cache
                  restore-keys: |
                      mkdocs-material-

            - run: |
                  pip install mkdocs-material
                  bash .devcontainer/requirements.sh

            - run: |
                  mkdocs build --site-dir _site/

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3

    deploy:
        runs-on: ubuntu-latest
        needs: build

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
